### ISSUE TITLE
could not find `Config` in `runc`

### ISSUE THREAD

**Issue by dierbei** [containerd/rust-extensions#157]
I want to try `runc` crate to run example code：
```rust
use runc;

#[tokio::main]
async fn main() {
    let config = runc::Config::new()
        .root("./new_root")
        .debug(false)
        .log("/path/to/logfile.json")
        .log_format(runc::LogFormat::Json)
        .rootless(true);

    let client = config.build_async().unwrap();

    let opts = runc::options::CreateOpts::new()
        .pid_file("/path/to/pid/file")
        .no_pivot(true);
    
    client.create("container-id", "path/to/bundle", Some(&opts)).unwrap();
}
```
```toml
[dependencies]
tokio = { version = "1.29.1", features = ["full"] }
runc = { git = "https://github.com/containerd/rust-extensions", features=["async"] }
```

But I ran into an error：

![image](https://github.com/containerd/rust-extensions/assets/52097565/506d3df7-b508-4360-900d-15517e9a52cc)
