### ISSUE TITLE
runc-shim does not support options

### ISSUE THREAD

**Issue by z63d** [containerd/rust-extensions#377]
Start the pod using runc shim.

I set it up like this. Of course this works.

`containerd/config.toml`
```toml
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc-v2-rs]
  runtime_type = "/home/kaita_nakamura/rust-extensions/target/release/containerd-shim-runc-v2-rs"
```

Next, add SystemdCgroup options.
```toml
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc-v2-rs.options]
  SystemdCgroup = true
```

`kubectl describe pod`
```
  Warning  FailedCreatePodSandBox  6s (x3 over 32s)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to start shim: start failed: io.containerd.runc.v2-rs: Other("add task to cgroup: unable to write to a control group file /sys/fs/cgroup/SystemdCgroup = true\n/cgroup.procs, value [CREATE FILE] caused by: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }")
: exit status 1: unknown
```

Other options are similar.
```
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc-v2-rs.options]
  NoNewKeyring = false
```
```
  Warning  FailedCreatePodSandBox  11s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to start shim: start failed: io.containerd.runc.v2-rs: Other("add task to cgroup: unable to write to a control group file /sys/fs/cgroup/NoNewKeyring = false\n/cgroup.procs, value [CREATE FILE] caused by: Os { code: 2, kind: NotFound, message: \"No such file or directory\" }")
: exit status 1: unknown
```

---

background: https://cloud-native.slack.com/archives/C04LTPB6Z0V/p1739716368576559?thread_ts=1738110849.528919&cid=C04LTPB6Z0V

I tried this with runwasi but it didn't work.
So I realized something was wrong.
https://github.com/containerd/rust-extensions/blob/shim-v0.8.0/crates/runc-shim/src/runc.rs#L85-L88

```
time="2025-02-16T13:37:36.859682982Z" level=debug msg="runwasi: opts: Options { no_pivot_root: false, no_new_keyring: false, shim_cgroup: "NoNewKeyring = false\nSystemdCgroup = true\n", io_uid: 0, io_gid: 0, binary_name: "", root: "", criu_path: "", systemd_cgroup: false, criu_image_path: "", criu_work_path: "", special_fields: SpecialFields { unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 44 } } }"
```
